CXX = g++
CXXFLAGS = -std=c++0x 

SRCS = langtonsAntMain.cpp intMenu.cpp Ant.cpp checkInt.cpp

HEADERS = intMenu.hpp Ant.hpp checkInt.hpp


langtonsAnt: ${SRCS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SRCS} ${HEADERS} -o langtonsAnt
	
clean:
	rm langtonsAnt


