#!/bin/bash
#####################################
# Program: compileall 
# Author: Jacob Leno
# Date: 06/09/18
####################################

gcc -o otp_enc_d otp_enc_d.c
gcc -o otp_enc otp_enc.c
gcc -o otp_dec_d otp_dec_d.c
gcc -o otp_dec otp_dec.c
gcc -o keygen keygen.c
